theme = "catppuccin_macchiato"

[editor]
scroll-lines = 1
cursorline = true
auto-save = false
completion-trigger-len = 1
true-color = true
color-modes = true
auto-pairs = true
rulers = [120]
idle-timeout = 50

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "⟩"
skip-levels = 1

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
# left = ["mode", "spinner", "file-name", "file-type", "total-line-numbers", "file-encoding"]
# center = []
#right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]
right = ["file-type","spacer", "version-control", "spacer", "diagnostics", "selections", "file-encoding", "file-line-ending", "position-percentage", "position"]

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"