icons = "awesome"

[theme]
name = "slick"
[theme.overrides]
idle_bg = "#303030"
idle_fg = "#C6C6C6"
info_bg = "#A83334"
info_fg = "#C6C6C6"
good_fg = "#C6C6C6"
warning_fg = "#C6C6C6"
critical_fg = "#C6C6C6"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
