; models.ini
version = 1

; Global settings
[*]
; n-gpu-layers = 0
models-max = 1
threads = 4
jinja = true
cache-reuse = 256
; top-p = 0.95 ; default
min-p = 0.0 ; default is 0.05
ctx-size = 16384 ; default is 4096

[granite4]
hf-repo = unsloth/granite-4.0-h-micro-GGUF:UD-Q4_K_XL
top-k = 20
temp = 0
ctx-size = 32768

[granite4-moe]
hf-repo = unsloth/granite-4.0-h-tiny-GGUF:UD-Q4_K_XL
top-k = 20
temp = 0

[gemma3]
hf-repo = lmstudio-community/gemma-3-4B-it-qat-GGUF:Q4_0
top-k = 64
repeat-penalty = 1.0
temp = 1.0
ctx-size = 32768

[gemma3-12b]
hf-repo = lmstudio-community/gemma-3-12B-it-qat-GGUF:Q4_0
top-k = 64
repeat-penalty = 1.0
temp = 1.0
ctx-size = 32768

[lfm2]
hf-repo = LiquidAI/LFM2-2.6B-GGUF:Q8_0
temp = 0.3
min-p = 0.15
repeat-penalty = 1.05
ctx-size = 32768

[lfm2-moe]
hf-repo = unsloth/LFM2-8B-A1B-GGUF:Q4_K_XL
temp = 0.3
min-p = 0.15
repeat-penalty = 1.05

[ministral3-3i]
hf-repo = mistralai/Ministral-3-3B-Instruct-2512-GGUF:Q4_K_M
temp = 0.15
min-p = 0.05

[ministral3-3r]
hf-repo = mistralai/Ministral-3-3B-Reasoning-2512-GGUF:Q4_K_M
temp = 0.7

[qwen-general-t-2b]
hf-repo = unsloth/Qwen3.5-2B-GGUF:Q4_K_XL
temp = 1.0
top-k = 20
presence-penalty = 1.5
repeat-penalty = 1.0
chat-template-kwargs = {"enable_thinking": true}

[qwen-code-t-2b]
hf-repo = unsloth/Qwen3.5-2B-GGUF:Q4_K_XL
temp = 0.6
top-k = 20
repeat-penalty = 1.0
chat-template-kwargs = {"enable_thinking": true}

[qwen-2b]
hf-repo = unsloth/Qwen3.5-2B-GGUF:Q4_K_XL
temp = 0.7
top-p = 0.8
top-k = 20
presence-penalty = 1.5
repeat-penalty = 1.0
chat-template-kwargs = {"enable_thinking": false}

[qwen-reason-2b]
hf-repo = unsloth/Qwen3.5-2B-GGUF:Q4_K_XL
temp = 1.0
top-p = 1.0
top-k = 40
presence-penalty = 2.0
repeat-penalty = 1.0
chat-template-kwargs = {"enable_thinking": false}

[qwen-general-t-4b]
hf-repo = unsloth/Qwen3.5-4B-GGUF:Q4_K_XL
temp = 1.0
top-k = 20
presence-penalty = 1.5
repeat-penalty = 1.0
chat-template-kwargs = {"enable_thinking": true}

[qwen-code-t-4b]
hf-repo = unsloth/Qwen3.5-4B-GGUF:Q4_K_XL
temp = 0.6
top-k = 20
repeat-penalty = 1.0
chat-template-kwargs = {"enable_thinking": true}

[qwen-4b]
hf-repo = unsloth/Qwen3.5-4B-GGUF:Q4_K_XL
temp = 0.7
top-p = 0.8
top-k = 20
presence-penalty = 1.5
repeat-penalty = 1.0
chat-template-kwargs = {"enable_thinking": false}

[qwen-reason-4b]
hf-repo = unsloth/Qwen3.5-4B-GGUF:Q4_K_XL
temp = 1.0
top-p = 1.0
top-k = 40
presence-penalty = 2.0
repeat-penalty = 1.0
chat-template-kwargs = {"enable_thinking": false}

[qwen-general-t-9b]
hf-repo = unsloth/Qwen3.5-9B-GGUF:Q4_K_XL
temp = 1.0
top-k = 20
presence-penalty = 1.5
repeat-penalty = 1.0
chat-template-kwargs = {"enable_thinking": true}

[qwen-code-t-9b]
hf-repo = unsloth/Qwen3.5-9B-GGUF:Q4_K_XL
temp = 0.6
top-k = 20
repeat-penalty = 1.0
chat-template-kwargs = {"enable_thinking": true}

[qwen-9b]
hf-repo = unsloth/Qwen3.5-9B-GGUF:Q4_K_XL
temp = 0.7
top-p = 0.8
top-k = 20
presence-penalty = 1.5
repeat-penalty = 1.0
chat-template-kwargs = {"enable_thinking": false}

[qwen-reason-9b]
hf-repo = unsloth/Qwen3.5-9B-GGUF:Q4_K_XL
temp = 1.0
top-p = 1.0
top-k = 40
presence-penalty = 2.0
repeat-penalty = 1.0
chat-template-kwargs = {"enable_thinking": false}
