; models.ini
;version = 1 ; triggers a bug creating a dummy "default" model

; Global settings
[*]
; n-gpu-layers = 0
parallel = 1
models-max = 1
threads = 4
jinja = true
cache-reuse = 256
top-p = 0.95 ; default
min-p = 0.0 ; default is 0.05
ctx-size = 8192 ; default is 4096 ; large is 32768

[gemma4-e2b]
hf-repo = unsloth/gemma-4-E2B-it-qat-GGUF:UD-Q4_K_XL
spec-type = draft-mtp
top-k = 64
temp = 1.0
ctx-size = 16384

[gemma4-e4b]
hf-repo = unsloth/gemma-4-E4B-it-qat-GGUF:UD-Q4_K_XL
spec-type = draft-mtp
top-k = 64
temp = 1.0

[gemma4-12b]
hf-repo = unsloth/gemma-4-12B-it-qat-GGUF:UD-Q4_K_XL
spec-type = draft-mtp
top-k = 64
temp = 1.0

[gemma4-26b]
hf-repo = unsloth/gemma-4-26B-A4B-it-qat-GGUF:UD-Q4_K_XL
spec-type = draft-mtp
top-k = 64
temp = 1.0
batch-size = 64
ubatch-size = 64
cache-type-k = q8_0
cache-type-v = q8_0
ctx-size = 16384

[ornith-9b]
hf-repo = protoLabsAI/Ornith-1.0-9B-MTP-GGUF:Q4_K_M
spec-type = draft-mtp
temp = 0.6
top_k = 20

[qwen-general-t-4b]
hf-repo = unsloth/Qwen3.5-4B-MTP-GGUF:Q4_K_XL
spec-type = draft-mtp
temp = 1.0
top-k = 20
presence-penalty = 1.5
repeat-penalty = 1.0
chat-template-kwargs = {"enable_thinking": true}

[qwen-code-t-4b]
hf-repo = unsloth/Qwen3.5-4B-MTP-GGUF:Q4_K_XL
spec-type = draft-mtp
temp = 0.6
top-k = 20
repeat-penalty = 1.0
chat-template-kwargs = {"enable_thinking": true}

[qwen-4b]
hf-repo = unsloth/Qwen3.5-4B-MTP-GGUF:Q4_K_XL
spec-type = draft-mtp
temp = 0.7
top-p = 0.8
top-k = 20
presence-penalty = 1.5
repeat-penalty = 1.0
chat-template-kwargs = {"enable_thinking": false}

[qwen-reason-4b]
hf-repo = unsloth/Qwen3.5-4B-MTP-GGUF:Q4_K_XL
spec-type = draft-mtp
temp = 1.0
top-p = 1.0
top-k = 40
presence-penalty = 2.0
repeat-penalty = 1.0
chat-template-kwargs = {"enable_thinking": false}
