# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/.powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

source "$HOME/.dotfiles/zsh/custom.zsh"
source "$HOME/.fsd/fast-syntax-highlighting.plugin.zsh"
source "$HOME/.customenv"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


# BEGIN opam configuration
# This is useful if you're using opam as it adds:
#   - the correct directories to the PATH
#   - auto-completion for the opam binary
# This section can be safely removed at any time if needed.
[[ ! -r /Volumes/ext/.opam/opam-init/init.zsh ]] || source /Volumes/ext/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null
# END opam configuration

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/marcelloseri/.cache/lm-studio/bin"

. "$HOME/.cargo/env"
